OpenMined/PipelineDP

pipeline_dp/pipeline_operations.py
tests/pipeline_operations_test.py

Adds a method for local map operation. See comment about a file change below.
Nope.
Tests added :test_tube: 
The empty `__init__.py` file has been added because without it pytest (and probably other testing frameworks?) cannot find `pipeline_dp` for importing (Python 3.8.5). I can imagine PyCharm users do not see the issue, but it will be needed for CI.

Add local map operation

---

.gitignore
pyproject.toml

Added support for poetry. Poetry is a package management tool that helps to setup your environment super quickly. More on it here: https://python-poetry.org/

Added Poetry support

---

pipeline_dp/pipeline_operations.py
tests/pipeline_operations_test.py

Adds every other remaining method to `LocalPipelineOperations` (we split work with Zachery).
None.
Unit tests added :broom:

Add more local pipeline operations

---

pipeline_dp/dp_engine.py
tests/dp_engine_test.py

- This PR changes `DPEngine` to use the `ReportGenerator` which constructs the explain plan for issue #10.
Part of #10 
- `dp_engine_test` adds two reports and checks that they are valid
- Tested with `conda` environment under `Python 3.8`

Add explain plan to dp_engine and test

---

pipeline_dp/__init__.py
pipeline_dp/dp_engine.py
pipeline_dp/pipeline_operations.py
tests/dp_engine_test.py
tests/pipeline_operations_test.py

Implementing Per partition - bounding of each contribution and cross partition. Added flat map in pipeline_operations.py to accommodate this functionality. Continuation of https://github.com/OpenMined/PipelineDP/pull/26
- Unit tests for bounding
- [x ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)

Contribution Bounding - per partition and cross partition bounding - continued from #26 pull request

---

pipeline_dp/budget_accounting.py
requirements.dev.txt
tests/budget_accounting_test.py

Functionality that gives the user the ability to input epsilon and delta values, compute a pipeline budget where the noise is adjusted for the given epsilon.
_Input_: Epsilon and Delta, _Output_: Minimized noise
Related to #35 
N/A
Unit tests where the calculated noise value is compared to the noise value returned by the PLD library for the same epsilon and delta. 
eg. 
```
compare_pld = accountant._compose_distributions(expected_noise)
self.assertAlmostEqual(epsilon, compare_pld.get_epsilon_for_delta(delta), 3)
```
The `expected_noise` should match the calculated noise from PipelineDP because the same epsilon and delta are input.
```
accountant = PLDBudgetAccountant(epsilon, delta)
accountant.compute_budgets()
self.assertEqual(expected_noise, accountant.minimum_noise)
```

PLD budget accountant

---

pipeline_dp/dp_computations.py
pipeline_dp/pipeline_operations.py
tests/budget_accounting_test.py
tests/dp_computations_test.py
tests/pipeline_operations_test.py

Implement reduce_accumulators_per_key in BeamOperations.
As the accumulators interface is still work in progress, this assumes the interface agreed in the documentation.
None
- Added unit tests

Implement reduce_accumulators_per_key in BeamOperations.

---

pipeline_dp/__init__.py
pipeline_dp/dp_engine.py
pipeline_dp/pipeline_operations.py
requirements.dev.txt
tests/dp_engine_test.py

Implementation of pipelined `_select_private_partitions` as specified in #8 using `pydp.algorithms.partition_selection.PartitionSelectionStrategy`. 
**New Dependency:** OpenMined/PyDP aka `python-dp`.
- Mocking `create_*_parititon_strategy` to deterministically generate private partitions.
- Passing toy data through the `_select_private_partitions` function
- Measuring expected result against outcome

Implementation of `_select_private_partitions`

---

pipeline_dp/pipeline_operations.py
tests/pipeline_operations_test.py

I added local reduce accumulators by key. I also removed the duplicate local_group_by_key test. Fixes #42 
I'm getting these errors but I'm not sure if they're related to my Python environment being messed up or if they're somehow related to my change.
=========================================================================================== short test summary info ===========================================================================================
FAILED tests/dp_computations_test.py::MeanVarParams::test_compute_dp_mean - AssertionError: 10000.259218047117 != 10000 within 0.1 delta
FAILED tests/dp_engine_test.py::dp_engineTest::test_aggregate_report - AttributeError: 'NoneType' object has no attribute 'filter_by_key'
FAILED …

Add local reduce accumulators by key

---

pipeline_dp/pipeline_operations.py
requirements.dev.txt
tests/pipeline_operations_test.py

Created a `multiprocessing` equivalent of `LocalPipelineOperations`, but with `n_jobs`. Most of the functionality should be exactly the same as `LocalPipelineOperations` but run on multi-threaded environment.  
Differences are:
- `MultiProcLocalPipelineOperations.group_by_key`, `samples_fixed_per_key` and `count_per_element` will be **out of order** because the processes contributing to the groups are running out of order, even if `ordered=True` was passed.
- ~We cannot guarantee full laziness of any of the functions. `multiprocessing` strives when we use "partial laziness", i.e. we launch jobs asynchronously and return sometime later to collect the results. During this time - the process pool works to later provide us with immediate results.~ EDIT: No longer true. Implemented classes …

Added MultiProcLocalPipelineOperations

---

Makefile
examples/movie_view_ratings.py
pipeline_dp/dp_engine.py

This PR contains the following changes:
1.Using LocalOperations in the example
2.Minor fixes of API usage (e.g. calling budget_account.compute_budgets() etc).
3.Limiting metrics only to COUNT (all others are not implemented yet)
4.Minor fix in dp_engine.aggregate (map_tuple -> map)  (it's not tested yet, since dp_engine.aggregate is not fully implemented), w/o this fix the example crashes instead of returning an intermediate result.
5.Making some flags to be required
6.Added examples folders for formating by `make format`

Improvement of the movie view example

---

pipeline_dp/dp_engine.py
tests/accumulator_test.py
tests/budget_accounting_test.py
tests/dp_computations_test.py
tests/dp_engine_test.py

A merge caused dp_engine_tests.py to start failing so I fixed that. Github actions was also failing so I ran the formatter.
I also updated the MeanVarParams tests to start passing consistently. I did this by increasing the delta which seemed fine with such large results, but let me know if you'd rather we change the inputs to reach a smaller delta.
N/A
- Unit tests

Fix failing tests caused by merge and format project.

---

pipeline_dp/pipeline_operations.py
tests/pipeline_operations_test.py

map_tuples was implemented as map in SparkRDDPipelineOperation. This PR fixes that and adds tests.
Along the way, the creation of SparkRDDOperations() was moved to setUpClass(cls), to match BeamOperations unittests.

Fix for spark map_tuple

---

examples/movie_view_ratings.py
pipeline_dp/accumulator.py
tests/accumulator_test.py

In order to apply private partition selection ([doc](https://github.com/google/differential-privacy/blob/main/common_docs/Differential_Privacy_Computations_In_Data_Pipelines.pdf), section **Private partition selection**, page 12) it's required to know privacy id count per partition key. This PR implements computation of  privacy id count in `CompoundAccumulator`. 
**Note:** Since we need to have `privacy_id_count`, the optimization which returns specific Accumulator (instead of `CompoundAccumulator`) is removed.
This PR also contains some small polishing.

Computing privacy id count in CompoundAccumulator

---

examples/movie_view_ratings.py
pipeline_dp/__init__.py
pipeline_dp/accumulator.py
pipeline_dp/budget_accounting.py
pipeline_dp/dp_engine.py
tests/dp_engine_test.py

This PR finishes implementation of the computation graph (which is implemented by `DPEngine.aggregate` ) for computing DP metrics with private partition selection.

Making aggregate with private partition selection work

---

examples/movie_view_ratings.py
pipeline_dp/accumulator.py
pipeline_dp/aggregate_params.py
pipeline_dp/dp_engine.py
tests/accumulator_test.py
tests/dp_engine_test.py
tests/report_generator_test.py

Add functionality for SumAccumulator through SumParams.
None.
- `GenericAccumulatorTest.test_create_accumulator_params_with_sum_params`
- `SumAccumulatorTest.test_without_noise`
- `SumAccumulatorTest.test_with_noise`
- `movie_view_ratings.calc_dp_rating_metrics`

Add SumParams to movie example and tests

---

.github/workflows/tests.yml

`if [ -f ... ]` doesn't work on Windows. And it looks we don't need to check existing of this file, so it's better to remove it.
**Note:** There are tests that are still failing on Windows namely 
```
pipeline_operations_test.py::SparkRDDOperationsTest::*
pipeline_operations_test.py::MultiProcLocalPipelineOperationsTest::*
```
Separate issues for fixing these tests will be created.

Fix run tests action on Windows

---

examples/movie_view_ratings.py
pipeline_dp/dp_engine.py
pipeline_dp/pipeline_operations.py
tests/pipeline_operations_test.py

This PR changes elements of output collection of `DPEngine._drop_not_public_partitions` in order to make it consistent with the rest of `DPEngine.aggregate`, namely `_drop_not_public_partitions` now returns collection of data instead of (key, data).
Along the way
`PipelineOperation.filter_by_key` was slightly refactored
1. Remove any mentions of public partition in `filter_by_key`, since this function is more generic.
2. Remove data_extractors from `filter_by_key` arguments (since they are used in `_drop_not_public_partitions`)

Fix filtering of public partitions

---

pipeline_dp/aggregate_params.py
pipeline_dp/dp_engine.py
pipeline_dp/report_generator.py
tests/dp_engine_test.py
tests/report_generator_test.py

This adds the report generator stages for aggregate params and contribution bounding.
It also adds a helper method for the tests so that they do not break when testing private functions.
It does not include the report stages for noise kind settings as this will be done following a refactoring. 
N/A
- dp_engine_test

Add report generator for dp_engine

---

tests/private_spark_test.py

There are some problems with the current setup of Spark on Windows

Disable spark tests on Windows

---

pipeline_dp/accumulator.py
pipeline_dp/dp_engine.py
tests/accumulator_test.py
tests/dp_engine_test.py

This PR is a refactoring of way how accumulators are created during aggregation. [`Accumulator`](https://github.com/OpenMined/PipelineDP/blob/0cb701891eca47c55ee2ba93bc1cf5470a30a242/pipeline_dp/accumulator.py#L57) is an object that does aggregation.
**Before this PR:**
`AccumulatorFactory` contains a list of `AccumulatorParams`. `AccumulatorParams` are used for creating accumulators during aggregation.
**After this PR:**
1. `AccumulatorFactory` is renamed to `CompoundAccumulatorFactory` 
2. Abstract `AccumulatorFactory` is introduced and concrete `AccumulatorFactory` creates corresponding accumulators (e.g.`CountAccumulatorFactory` creates `CountAccumulator`)
**Why this refactoring is needed?**
This PR is 1st step of refactoring of computing metrics with `CombineFn` functions (see [on …

Introduce AccumulatorFactory hierarchy

---

pipeline_dp/dp_engine.py

Minor fix for the filter function, now we are directly using the budget in the outer scope.

Fixes capture for filter_fn.

---

pipeline_dp/aggregate_params.py
pipeline_dp/private_beam.py
tests/private_beam_test.py

Add PrivacyIdCount Transform to Beam's public API.
Make test names more descriptive and change test names to a consistent format (snake case).
- Unit tested.

Add PrivacyIdCount Transform to Beam's public API.

---

pipeline_dp/pipeline_backend.py
tests/pipeline_backend_test.py

This is a part of accumulator framework to combiner framework refactoring
`combine_accumlators_per_key` corresponds to [reduce_per_key](https://github.com/OpenMined/PipelineDP/blob/0d92d0d44bfb5f88f7fc0929dfda6efc7e020e30/pipeline_dp/pipeline_backend.py#L77) in accumulator framework.
Along the way pipelines_operations_test was renamed to pipelines_backend_test

Introduce combine_per_key in PipelineBackend

---

pipeline_dp/accumulator.py
pipeline_dp/combiners.py
pipeline_dp/dp_engine.py
tests/combiners_test.py
tests/dp_engine_test.py

This PR:
1.Fixes dp_engine_test, which were broken after [PR](https://github.com/OpenMined/PipelineDP/pull/156) which introduced usage of CombinerFramework instead of Accumulator Framework
2.Adds tests for PrivacyIdCombiner and CreateCompoundAccumulator

Combiner tests

---

pipeline_dp/dp_engine.py
tests/private_spark_test.py

This PR contains:
1. Fix for sampling inside inside select_private_partition (more details in comments in code) which fixes running select partitions in Beam
2. Fixes in stage names
3. A simple fix for private_spark tests (removed setting not existed anymore variable)

Fix select partitions

---

pipeline_dp/private_spark.py
tests/private_spark_test.py

Add Privacy ID Count Transform to Spark's public API.
- use f-string.
Unit tested.

Spark privacy id count

---

.github/workflows/publish.yml
Makefile
pipeline_dp/__init__.py
pyproject.toml
setup.cfg
setup.py

added support for release on PyPI

---

pipeline_dp/budget_accounting.py
tests/budget_accounting_test.py

This PR introduces finalized state to Budget Accountant. Which ensures that budget can't be requested after `compute_budgets` is called

Ensure that budget can not be used twice

---

tests/private_beam_test.py

There seems to be some bugs around long values in pyspark on older python versions. This PR replaces the numbers in the broken tests with float
```
E   RuntimeError: VarLong too long.
```

Fix type error in beams tests on Windows.

---

pipeline_dp/private_spark.py
tests/private_beam_test.py
tests/private_spark_test.py

Add select_partitions() to private_spark
Add select_partitions() to private_spark. Fix typo in the select_partitions() tests in private_beam
- Unit tests

Add select_partitions() to private_spark

---

pipeline_dp/private_spark.py
tests/private_spark_test.py

private_spark aggregations new tests and small fixes
- Add "*_returns_sensible_result" tests to the rest of private_spark aggregations
- Make all tests style and structure in private_spark_tests consistent with each other
- Fix configuration error in the count implementation of private_spark
- Unit tests

private_spark aggregations new tests and small fixes

---

setup.py

Adds utility analysis in packages. After building and installing, users should be able to import utility analysis library by using `import utility_analysis` directly.
Tested locally and install from the wheel file. It seems to work for me

Adds utility analysis in packages.

---

pipeline_dp/dp_computations.py
tests/dp_computations_test.py

This PR fixes:
min_value = max_value = 0 => dp_sum = 0
min_value = max_value => dp_mean = min_value

Fix corner cases for DP mean and sum computations

---

README.md

Came here via https://www.infoq.com/news/2022/02/differential-privacy-python/ and noticed a tiny grammar error int he README
N/A
Double-checked in MS Word.
Unsure how to add the label, but it's type: Documentation.

Fix small grammar error (it's -> its)

---

utility_analysis/data_peeker.py

Similar to #235 don't error if pyspark or apache beam aren't available

utility_analysis: Make spark and beam optional deps

---

README.md
examples/movie_view_ratings/run_all_frameworks.py
pipeline_dp/aggregate_params.py
pipeline_dp/budget_accounting.py
pipeline_dp/combiners.py
pipeline_dp/dp_computations.py
pipeline_dp/dp_engine.py
pipeline_dp/pipeline_backend.py
pipeline_dp/private_beam.py
pipeline_dp/private_spark.py
tests/budget_accounting_test.py
tests/combiners_test.py
tests/dp_computations_test.py
tests/dp_engine_test.py
tests/pipeline_backend_test.py
tests/private_beam_test.py
tests/private_spark_test.py
utility_analysis/non_private_combiners.py

Closes #255
Adds support for the calculation of variance in PipelineDP. Changes cover all places where mean was used since variance and mean are very close to each other.
None
It was tested by unit tests. If a unit test exists for the mean then similar test was added for variance.
- [] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)

Add variance calculations in PipelineDP

---

examples/movie_view_ratings/run_all_frameworks.py
pipeline_dp/__init__.py
pipeline_dp/aggregate_params.py
pipeline_dp/combiners.py
tests/combiners_test.py

Following the first item described in #264, this PR has the implementation of the `VectorSumCombiner` class, which should be used to compute vector/array sums.
Needed to extend [AggregateParams](https://github.com/OpenMined/PipelineDP/blob/3a7b87a5d943ea6b083c45934c8bb1110cbe5766/pipeline_dp/aggregate_params.py#L56) with the fields `norm_kind` and `max_norm`.
* Tests added to `combiners_test.py`
```
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.9.10, pytest-7.1.2, pluggy-1.0.0
plugins: timeout-2.1.0
collected 45 items …
```

Implementing VectorSumCombiner

---

pipeline_dp/combiners.py
pipeline_dp/dp_computations.py
tests/combiners_test.py
tests/dp_computations_test.py
tests/private_beam_test.py
tests/private_spark_test.py

This PR introduces an improvement for the numerical stability of DP mean and variance computations as per #287.
This is done by computing the normalized sum in the accumulator of the mean combiner.  
For computing variance the sum and the squares sum are both normalized in the accumulator of the variance combiner.
N/A
- Existing tests for the mean and variance combiners where refactored to test the normalized sum instead of sum
- Existing tests in `dp_computations` were refactored to call `compute_dp_mean` and `compute_dp_var` methods correctly with normalized sum instead of total sum

Improvement: numerical stability of DP mean and variance computations as per #287

---

utility_analysis_new/combiners.py
utility_analysis_new/dp_engine.py
utility_analysis_new/tests/combiners_test.py

This accumulator is needed for computation of probability that the partition is kept. Computations of that probability will be in the subsequent PRs.

Implementation of partition selection accumulator

---

pipeline_dp/dp_engine.py
pipeline_dp/pipeline_backend.py
tests/pipeline_backend_test.py

This PR fixes intricated problem inside Beam code. The idea is that Beam PTransforms should be applied to beam PCollection. While applying them to Python list is possible, it might lead to exceptions in complicated pipelines.

Convert public partitions to PCollection

---

pipeline_dp/pipeline_backend.py
tests/pipeline_backend_test.py

`to_collection` a function which converts to the framework collection. This PR fixes it for `BeamBackend`, namely if the input is already `PCollection`, then this function should be no-op.
This fixes using `PCollection` as `public_partitions`  for `BeamBackend`.

Fix to_collection

---

examples/restaurant_visits/run_without_frameworks_tuning.py
pipeline_dp/budget_accounting.py
pipeline_dp/input_validators.py
tests/dp_engine_test.py
utility_analysis_new/__init__.py
utility_analysis_new/parameter_tuning.py
utility_analysis_new/tests/utility_analysis_test.py
utility_analysis_new/utility_analysis.py

This CL contains multiple minor improvements:
1. Renaming `tune_parameters()` -> `tune()` and added `backend` argument
2. Simplified tune API: `ParametersToTune` changed to bool arguments 
3. Added example of using tune API (which is mostly copy of utility_analysis example)
4. Validation for (eps, delta) extracted to separete file (and added in a few places)
5. Renaming `eps` -> `epsilon` in `UtilityAnalysisOptions`

Tuning polishings

---

pipeline_dp/dp_computations.py
tests/dp_computations_test.py

This PR adds a method which computes the standard deviation of the noise added to DP-sum aggregations. 
N/A
- New tests were added for `compute_dp_sum_noise_std`

Compute the standard deviation for DP-sum noise.

---

utility_analysis_new/combiners.py
utility_analysis_new/tests/utility_analysis_test.py

Setting errors to inf, make the result inf, i.e. for any public partitions the result is inf. While it's a good question how to count relative error for added empty partitions, returning inf doesn't sound as a good option

Setting 0 for relative errors when actual value = 0

---

pipeline_dp/combiners.py
utility_analysis_new/combiners.py
utility_analysis_new/dp_engine.py
utility_analysis_new/tests/combiners_test.py
utility_analysis_new/tests/dp_engine_test.py

This is done for performance reasons - it's much faster to work with tuples and serialized size of tuples is ~10 times smaller.
It turned out that the changes are pretty small and the resulting code structuring is nice:
1. Before:
```
def create_accumulators():
...
return Accumulator(...)
```
After
```
def create_accumulators():
...
return (...)  # the same code, just Accumulator name dropped
```
2. Before
```
def compute_metrics(acc)
```
After
```
def compute_metrics(acc)
field1, field2.. = acc 
```
Also, it's introduced a base class for UtilityAnalysisCombiners.

Refactoring: Using tuples instead of dataclasses for Utility Analysis accumulators.

---

utility_analysis_new/combiners.py
utility_analysis_new/contribution_bounders.py
utility_analysis_new/dp_engine.py
utility_analysis_new/tests/combiners_test.py

This PR is huge performance improvements, especially in case when Utility Analysis runs for many parameters:
It introduces a sparse mode for UtilityAnalysis accumulators, namely instead of creating many accumulators for each privacy id contribution (which can be 100s times larger than the original data), it keeps counts/sums of the original data in UtilityAnalalysisCompoundAccumulator , until there are many data points and only then the internal accumulators are created.

Sparse mode for utility analysis accumulators

---

examples/movie_view_ratings/run_without_frameworks.py
pipeline_dp/aggregate_params.py
pipeline_dp/combiners.py
requirements.dev.txt
tests/combiners_test.py
tests/dp_engine_test.py
tests/report_generator_test.py

This PR implements DP percentile computations.
API:
It adds metric `metrics.Percentile`, so now it's possible to compute percentiles with `DPEngine.aggregate`
`dp_engine.aggregate(... metrics=[metrics.Count, metrics.Percentile(50), metrics.Percentile(90)] ...)`
The result looks like:
(8, MetricsTuple(count=14532.95396910912, percentile_50=2.9999810443476416, percentile_90=4.99996013795033))
Implementation:
1. `Metrics`: previously it was `enum`, but metrics.Percentile(50) can't be implemented with enum, so `Metric` class was implemented.
2. `QuantileCombiner` is implemented. It uses `QuantileTree` object which is wrapper from PyDP for [the object](https://github.com/google/differential-privacy/blob/main/cc/algorithms/quantile-tree.h) from Google C++ building block library

DP percentiles

---

examples/restaurant_visits/run_without_frameworks_tuning.py
utility_analysis_new/parameter_tuning.py
utility_analysis_new/tests/parameter_tuning_test.py
utility_analysis_new/utility_analysis.py

**Context:**
[`perform_utility_analysis`](https://github.com/OpenMined/PipelineDP/blob/b186cbdd2d7cc1794afe1b50be2f46a8cbdf8b12/utility_analysis_new/utility_analysis.py#L47)  the following way:
1. Errors per partitions are computed
2. Aggregated metrics from all partitions are computed
Now it returns only aggregated metrics. But sometimes errors per partitions are useful, for example for computing another aggregated metrics. This PR implements that

Return per partition utility analysis

---

examples/restaurant_visits/run_without_frameworks_utility_analysis.py
pipeline_dp/sampling_utils.py
tests/sampling_utils_test.py
utility_analysis_new/contribution_bounders.py
utility_analysis_new/dp_engine.py
utility_analysis_new/tests/contribution_bounders_test.py
utility_analysis_new/tests/dp_engine_test.py
utility_analysis_new/utility_analysis.py

This PR implements sub-sampling of partitions for utility analysis.
It works the following:
1.`UtilityAnalysisEngine.aggregate` has sampling_probability
2. Utility analysis ContributionBounder can perform sub-sampling of partitions using `ValueSampler` if sampling probability < 1.0
3. `ValueSampler` computes hash of partition key and if the hash (which is assumed to return uniform values) is less than sampling_rate*max_hash_value, the partition_key is kept.

Sampling per partitions

---

pipeline_dp/dp_engine.py
pipeline_dp/pipeline_backend.py
tests/pipeline_backend_test.py
utility_analysis_new/__init__.py
utility_analysis_new/histograms.py
utility_analysis_new/parameter_tuning.py
utility_analysis_new/tests/histograms_test.py
utility_analysis_new/tests/parameter_tuning_test.py

This PR implements computing of histograms for `(partition_key, count)` (i.e. how many partitions have count=1, how many partitions have count=2, ... )   and `(partition_key, privacy_id_count)` (i.e. how many partitions have privacy_id_count=1, how many partitions have privacy_id_count=2, ... ).
Those are the same histograms which are used for computing cross and per partition contributions per privacy_id.
These histograms will be used in parameter tuning.

Computing partition count histograms

---

utility_analysis_new/combiners.py
utility_analysis_new/tests/combiners_test.py

float takes less space when serializing, leading to performance improvements as data is passed around workers.

Use float instead of np.float64

---

utility_analysis_new/__init__.py
utility_analysis_new/data_structures.py
utility_analysis_new/dp_engine.py
utility_analysis_new/parameter_tuning.py
utility_analysis_new/tests/utility_analysis_test.py
utility_analysis_new/utility_analysis.py

This is refactoring PR.
Dataclasses `MultiParameterConfiguration` and `UtilityAnalysisOptions` moved to data_structures.py

Moving dataclasses to a separate file

---

examples/restaurant_visits/run_without_frameworks_utility_analysis.py
pipeline_dp/__init__.py
utility_analysis_new/dp_engine.py
utility_analysis_new/tests/dp_engine_test.py
utility_analysis_new/utility_analysis.py

This is a refactoring PR which contains the following changes.
1. Renaming `DPEngine.aggregate` -> `DPEngine.analyze` (this function performs analysis, not DP aggregation)
2. This function now takes `UtilityAnalysisOptions` instead of bunch of paramers

Refactor UtilityAnalysisEngine.analyze

---

pipeline_dp/pipeline_backend.py

This is convenient, since sometimes it's needed to generate unique labels also in code which uses PipelineDP

Expose UniqueLabelGenerator from BeamBackend

---

examples/restaurant_visits/run_without_frameworks_tuning.py
examples/restaurant_visits/run_without_frameworks_utility_analysis.py
pipeline_dp/dp_engine.py
utility_analysis_new/__init__.py
utility_analysis_new/combiners.py
utility_analysis_new/contribution_bounders.py
utility_analysis_new/data_structures.py
utility_analysis_new/dp_engine.py
utility_analysis_new/parameter_tuning.py
utility_analysis_new/tests/combiners_test.py
utility_analysis_new/tests/contribution_bounders_test.py
utility_analysis_new/tests/dp_engine_test.py
utility_analysis_new/tests/utility_analysis_test.py
utility_analysis_new/utility_analysis.py

This PR implements running utility analysis on pre-aggregated data (previously it was possible only on the raw data).
The implementations consists of the following:
1. The extracting of needed columns (e.g. privacy_id, partition_key) with extractors is moved to a separate `DPEngine._extract_columns` method which is overriden in UtilityAnalysisEngine (because for pre-aggregated data the different data extraction).
2. Computing of count, sum per `(privacy_id, partition_key)` was moved from `CompoundCombiner` to `ContributionBounding` (that's because count and sum is already computed in for per-aggregated data)
3. Introduced `NoOpContributionBounder` for using for pre-aggregated data (because all that needed for contribution bounding is already computed in pre-aggregted data).
4. …

Run utility analysis on pre-aggregated data

---

analysis/combiners.py
analysis/metrics.py
analysis/tests/combiners_test.py
analysis/tests/dp_engine_test.py
analysis/utility_analysis.py
analysis/utility_analysis_engine.py

both for per-partition and cross-partition aggregation.

Refactoring of Combiners, PrivacyIdCount and Count now use Sum

---

tests/dp_computations_test.py

dp_compute_test.test_compute_dp_sum seemed to be using a wrong formula to compute lInf sensitivity. The result of the formula was correct by chance because of the combination of values. This PR fixes the formula.

Fix linf sensitivity computation in DP sum tests of dp_compute_test

---

analysis/tests/utility_analysis_engine_test.py
analysis/utility_analysis_engine.py
examples/restaurant_visits/run_without_frameworks_utility_analysis.py

##What was broken?
For simplicity assume that `metrics=[count, sum]` and there are 2 configurations to compute - `max_partition_contributed = [1,2]`.
For computing each metric for each input configuration `UtilityAnalysisCombiner` is created, before this PR the code was the following
```
for metric in metrics:
for configuration in configurations:
budget = request_budget()
// create  combiner
```
The problem is that it requests budget 2*2 = 4 times. Which is incorrect, since different configurations have different budget. This PR fixes that by ensuring that for each metric independently of the number of configurations `request_budget` is called once.

Fix split budget for multi configuration in Utility Analysis

---

pipeline_dp/aggregate_params.py
pipeline_dp/private_spark.py
tests/private_spark_test.py

When the input dataset already contains a limited number of records per individual, `contributions_already_enforced = True` can be used. As a result no contribution bounding happens

Expose contributions_already_enforced in SparkAPI

---

examples/movie_view_ratings/run_on_beam.py
examples/movie_view_ratings/run_on_spark.py
examples/movie_view_ratings/run_without_frameworks.py
pipeline_dp/__init__.py
pipeline_dp/dp_engine.py
pipeline_dp/private_beam.py
pipeline_dp/private_spark.py
pipeline_dp/report_generator.py
tests/report_generator_test.py

This PR contains the following changes:
1.Introducing `ExplainComputationReport` class which is a container for explain computation report.
2.Adding `ExplainComputationReport` to `DPEngine.aggregate` arguments, for returning the report.
3.Adding `ExplainComputationReport` to Beam and Spark APIs.
4.Updating examples
```
DPEngine method: aggregate
AggregateParams:
metrics=['SUM']
noise_kind=laplace
budget_weight=1
Contribution bounding:
max_partitions_contributed=2
max_contributions_per_partition=1
min_value=1
max_value=5
Partition selection: private partitions
Computation graph:
1. Per-partition contribution bounding: for each privacy_id and eachpartition, randomly select max(actual_contributions_per_partition, 1) contributions.
2. Cross-partition contribution bounding: for each privacy_id …
```

Expose explain computations in API

---

examples/codelab/codelab_PipelineDP.ipynb

This PR fixes the description of how to use public partititions. The code has been updated to pass public_partitions to dp_enging.aggregate, but the description still referred to the Params class. 
List any dependencies that are required for this change.
- no test required, only markdown change.

fix to description of usage of public partitions

---

pipeline_dp/pipeline_backend.py
pipeline_dp/private_beam.py
tests/pipeline_backend_test.py
tests/private_beam_test.py

Apache Beam requires that all stage_names were different. `pipeline_dp.BeamBackend` object ensures the uniqueness of the Beam stage names. But it is required to have the same object `BeamBackend` for all operations in private_beam.py.
This PR implements does by introducing a module level variable `_beam_backend` for this.

Fix handling stage names in private_beam

---

analysis/data_structures.py
analysis/tests/data_structures_test.py
analysis/tests/utility_analysis_engine_test.py

This CL introduces the possibility to run multi-parameter Utility analysis with different `noise_kind` and `partition_selection_strategy`.

Extend muti parameter analysis configuration with noise_kind and partition_selection_strategy

---

analysis/cross_partition_combiners.py
analysis/metrics.py
analysis/tests/cross_partition_combiners_test.py

This refactoring is about introducing new output dataclasses for cross-partition utility metrics. It includes the following parts.
1. Introducing the new dataclasses, [PR](https://github.com/OpenMined/PipelineDP/pull/400)
2. Converting per-partition utility metric for 1 partition to a cross partition utility metric (this PR) 
3. Combining  cross partition utility metric (next PRs), the new combiners for that (in cross_partition_combiner.py)
4. Updating `perform_utility_analysis` for using new combiners.

Refactor analysis output metrics: part 2 Per-partition utlity metrics to cross-partition

---

analysis/cross_partition_combiners.py
analysis/metrics.py
analysis/tests/cross_partition_combiners_test.py

Merge is needed in order to aggregate cross-partition metrics over dataset

Refactor analysis output metrics: part 6 Merging cross-partition utility metrics

---

analysis/cross_partition_combiners.py
analysis/metrics.py
analysis/tests/cross_partition_combiners_test.py

This PR
1. Introduces CrossPartitionCombiner for computing utility global (i.e. cross-partition) analysis metrics 
2. All information about partitions (incl. partition selection) is now in `PartitionMetrics` (previously `PrivatePartitionSelectionMetrics` ), which addresses one of the inconsitencies previosly that Count Metrics contain information about partitions

Refactor analysis output metrics: part 7 Cross-partition metrics combiner

---

analysis/parameter_tuning.py
analysis/tests/parameter_tuning_test.py
examples/restaurant_visits/run_without_frameworks_tuning.py

This PR implements `tune_new` which uses `perform_utility_analysis_new` and returns new the result in new dataclasses.
Note: after migrating old code, the old `tune` will be dropped and `tune_new` will be renamed to `tune`

Refactor analysis output metrics, part 9: tune using perform_utility_analysis_new

---

pipeline_dp/aggregate_params.py
pipeline_dp/dp_computations.py
tests/dp_computations_test.py

This is the part of the refactoring for making adding noise more OOP. This refactoring is for supporting PLD and l1 sensitivities in future.

Compute Sensitivities for COUNT, SUM, PRIVACY_ID_COUNT

---

tests/pipeline_backend_test.py

Make conditions for skipping PySpark tests more precise, enabling them on macOS and Windows, they work there.
The change affects tests only.
None
Tested by current tests.

Make conditions for skipping PySpark tests more precise

---

examples/movie_view_ratings/run_all_frameworks.py
pipeline_dp/combiners.py
pipeline_dp/dp_computations.py
tests/combiners_test.py
tests/dp_computations_test.py

This PR extends explain computation report by adding noise kind and noise parameters for count/privacy_id_count/sum. For other aggregation it will be added later
Now it looks like
5. Computed DP count with
Gaussian mechanism:  parameter=17.64452389929557  eps=0.3333333333333333  delta=3.333333333333333e-07  l2_sensitivity=1.4142135623730951
6. Computed DP sum with
Gaussian mechanism:  parameter=88.22261949647785  eps=0.3333333333333333  delta=3.333333333333333e-07  l2_sensitivity=7.0710678118654755
7. Computed DP privacy_id_count with
Gaussian mechanism:  parameter=17.64452389929557  eps=0.3333333333333333  delta=3.333333333333333e-07  l2_sensitivity=1.4142135623730951

Add noise in explain computation report

---

pipeline_dp/combiners.py

This PR changes order in which custom_combiner gets aggregate_params and budget_accountant. It's more logical in order
1.`AggregateParams`
2.`BudgetAccountant`
Since the budget request might depend on `AggregateParams`

Fix custom combiners

---

pipeline_dp/dp_computations.py
tests/dp_computations_test.py

The new code for DP mean was implemented in [PR](https://github.com/OpenMined/PipelineDP/pull/445).
Also flakiness for test distribution was decreased by changing consts.

Removing old DP mean computation code

---

analysis/metrics.py
analysis/tests/cross_partition_combiners_test.py
analysis/tests/utility_analysis_test.py
tests/dp_engine_test.py

There are also 2 changes in reformatting, which is caused that yapf formatter was updated recently in Github continuous testing system.

Renaming in UtilityReportBin

---

analysis/parameter_tuning.py
analysis/tests/parameter_tuning_test.py
analysis/tests/utility_analysis_test.py
analysis/utility_analysis.py
examples/restaurant_visits/run_without_frameworks_tuning.py

This argumen just adds complexity, let's return always per_partition results

(Polishing) Dropping return_per_partition argument

---

analysis/parameter_tuning.py
analysis/tests/parameter_tuning_test.py

If l0 candidate set is smaller than requested then we can add more candidates to linf candidate set and vice verca.

Add more candidates if l0/linf candidate sets have fewer candidates than requested

---

analysis/tests/parameter_tuning_test.py
pipeline_dp/combiners.py
pipeline_dp/dp_computations.py
tests/combiners_test.py
tests/dp_computations_test.py

Having 2 very similar classes `AdditiveMechanismSpec` and `MechanismSpec` adds confusions and complexity, while doesn't add any benefits. Let's drop the former and let's use  `MechanismSpec`.
Also it contains
1. test renaming, dropping "_new", which is leftover from `tune_new` (which was renamed to `tune`).
2. increase acceptance range for a stat tests (in tests/combiners_test.py).

(Refactoring) Drop AdditiveMechanismSpec, use MechanismSpec instead

---

analysis/parameter_tuning.py
analysis/tests/parameter_tuning_test.py

Now we construct candidates set based on generate_possible_contribution_bounds method that generates numbers that have 3 left-most digits non-zero and others are zero. I.e., it will be [1, 2, 3, ..., 999, 1000, 1010, 1020, ..., 9990, 10000, 10100, 10200.
This is not a pure logarithmic scale, it keeps relative difference between neighbouring almost the same across the candidates set (it varies from 0.1% to 1%). Such solution has a problem that beginning of the sequence can become very scarce due to sampling (we do sampling such sequence contains more than max_candidates values). It is bad because density in the beginning of the sequence should be higher, we need more elements there because a change there in absolute values affects the result much more than change in the right side of the …

Implement pure logarithmic grid for candidates search.

---

analysis/cross_partition_combiners.py
analysis/tests/utility_analysis_test.py

`PartitionInfo` contains information about the expected number of kept partition during the partition selection. But ithere was a bug, `PartitionInfo` was averaged across partitions. This PRs fixes that

Fix scaling partition info

---

analysis/parameter_tuning.py
analysis/tests/parameter_tuning_test.py
pipeline_dp/dataset_histograms/histograms.py

This is done mainly to simplify mocking, while there is no particular reason, namely mocking of properties are complicated, it requires mocking of classes, like
`setattr(mock_l0_histogram.__class__, 'max_value', 6)`
But such mocking is bad, because it changes value of `max_value` in **other tests** :(. For example the `test_count` in parameter_tuning.py was incorrect because of incorrect `max_value`.
The simplest solution is to make `max_value` to be method, which seems to be not worse than property.

Make histogram.max_value to be method instead of property

---

.github/workflows/publish.yml
.github/workflows/tests.yml
README.md
pyproject.toml
requirements.dev.txt
setup.py
tests/partition_selection_test.py

This PR contains:
1. Updating Python suported versions from Python 3.7-3.9 to Python 3.8-3.10, since 3.7 is already deprecated
2. Updating PyDP to the newest version
3. Enabling one test, which was disabled because of missing PyDP new features
Unfortunetely Windows builds fail, because PyDP failes to be built on Windows. This will be fixed soon.

Update supported Python versions and PyDP version

---

analysis/cross_partition_combiners.py
analysis/metrics.py
analysis/parameter_tuning.py
pipeline_dp/dataset_histograms/histogram_error_estimator.py
pipeline_dp/dp_computations.py
pipeline_dp/dp_engine.py

This PR contains the following changes:
1. Replacement `pipeline_dp.Metrics` -> `pipeline.Metric` (the difference: the type of metrics is `pipeline.Metric`, `pipeline_dp.Metrics` is a storage of of different metrics).
2. Replacement `pipeline_dp.budget_accountant.MechanismSpec` -> `budget_accountant.MechanismSpec` (because the former doesn't work in Colab)

Type annotation polishings

---

analysis/cross_partition_combiners.py
analysis/metrics.py
analysis/tests/cross_partition_combiners_test.py

Right now we just combine all partitions equally during utility analysis. We want to allow clients do it in a more elaborate way, giving them some set of predefined good weighing functions and allowing them to specify their own. For example, we can provide them with a weighing function that weighs based on the contribution of the partition (e.g. in case of COUNT metric, it is partitions size).

Add support for custom weight specification during cross partition combining

---

pipeline_dp/dp_engine.py

This PRs implements extracting `(privacy_id, partition_key, value)` from raw records as a first computation in `DPEngine.aggregate`. Previously it was done on later stages.
This has performance improvements, for cases when the input record are large.

Small refactoring in DPEngine

---

analysis/data_structures.py
analysis/tests/utility_analysis_test.py
analysis/utility_analysis.py

`UtilityReport` is the result of utility analysis. `peform_utility_analysis` can compute utlity analysis for different partition selection strategies, so it's needed to return partition selection strategy as  a part of `UtilityReport`

Add partition selection strategy for UtilityReport

---

analysis/tests/parameter_tuning_test.py
pipeline_dp/dataset_histograms/computing_histograms.py
pipeline_dp/dataset_histograms/histograms.py
pipeline_dp/pipeline_backend.py
pipeline_dp/pipeline_functions.py
tests/dataset_histograms/computing_histograms_test.py
tests/dataset_histograms/histogram_error_estimator_test.py
tests/dp_engine_test.py
tests/pipeline_backend_test.py
tests/pipeline_functions_test.py
tests/private_contribution_bounds_test.py

Linf sum contributions histogram is a histogram where bins (lowers) are X_1, X_2, ..., X_n, where X_i is sum of values that have same (pid, pk)-pair (rounded to the bucket). Count of such histogram is number of (pid, pk) that have this sum. Sum of such histogram is sum of all sums in this bucket.

Add support to compute linf sum contributions histogram

---

analysis/parameter_tuning.py
analysis/tests/parameter_tuning_test.py

Quantiles strategy which means picking up top 5 quantiles showed poor results, worse then constant relative step strategy. Therefore we remove it. From now on we will use only constant relative step strategy.

Remove quantiles strategy

---

analysis/utility_analysis_engine.py
pipeline_dp/aggregate_params.py
pipeline_dp/combiners.py
pipeline_dp/contribution_bounders.py
pipeline_dp/dp_engine.py
tests/combiners_test.py
tests/dp_engine_test.py

This PR introduces `combiner.expects_per_partition_sampling()` method.
If at least one combiner returns true from `expects_per_partition_sampling()`, sampling per partition is performed. Sampling in partition is required for `Mean/Variance/Quantiles`. On other hand, when SUM is computed with `min/max_sum_per_partition` contribution bounding, there should be no sampling, since SumCombiner at first sums per partition contributions and clips to `min/max_sum_per_partition`.

Do not sample per partition when min/max_sum_per_partitions is set

---

analysis/cross_partition_combiners.py
analysis/parameter_tuning.py
analysis/tests/cross_partition_combiners_test.py
analysis/tests/parameter_tuning_test.py

Uses `linf_sum_contributions_histogram` to compute that, candidates are taken as max values of bins, bins are sampled uniformly.
min_sum_per_partition is not implemented and is always zero.
utility analysis for sum was not implemented, this PR also adds support for it modifying `_sum_metrics_to_data_dropped` method.

Add logic for finding `max_sum_per_partition` candidates

---

analysis/cross_partition_combiners.py
analysis/per_partition_combiners.py
analysis/tests/per_partition_combiners_test.py
analysis/tests/utility_analysis_test.py
examples/restaurant_visits/run_without_frameworks_tuning.py

This PR contains propagating of `pre_threshold` to PyDP `PartitionSelectionStrategy` object which handles everything necessary for computing probability to keep partitions.

Utility analysis for pre-thresholding

---

examples/movie_view_ratings/run_all_frameworks.py
pipeline_dp/dp_engine.py

When `contribution_bounds_already_enforced = True` then PipelineDP does no contribution bounding. As a privacy id is not needed. The current validation requires `privacy_id_extractor` to be None, but there is no problem if privacy id extractor is set up. But it's pretty confusing for users why `privacy_id_extractor` has to be `None`. Let's drop this validation for simplicity

Remove not needed validation on privacy_id_extractor

---

examples/restaurant_visits/run_on_dataframes.py
pipeline_dp/dataframes.py
tests/dataframes_test.py

This PR intorduces `QueryBuilder.mean`, to allow DP mean computation. Along the way small refactoring done: allmost all validations are performed in `QueryBuilderbuild_query` instead of individual aggregation function (`count`, `sum` etc). That's more convenient, since the conditions on the correct state can be complicated, provided that in future the will be more aggregations and it will be allowed to compute aggregates of multiple columns.

Implement mean in DataFrame API

---

analysis/per_partition_combiners.py
analysis/tests/per_partition_combiners_test.py
analysis/utility_analysis_engine.py

`CombinerParams` class is not used anymore in production  combiners. Moreover it doesn't provide any benefits, it just contains 2 fields: `MechanismSpec` and `AggregateParams`. Let's stop using `CombinerParams` in utility analysis and pass `MechanismSpec` and `AggregateParams` directly. That would simplify the code a little bit.

(Refactoring) Drop using CombinerParams Class in Utility analysis combiners

---

analysis/tests/utility_analysis_engine_test.py
analysis/utility_analysis_engine.py
pipeline_dp/dp_engine.py

Having 1 budget allows having different `noise_kind` in different parameters in one run of utility analysis. Which is especially important since DPAlgorithmSelector can choose different `noise_kind`

Implement 1 BudgetAccount per one configuration in utility analysis

---

examples/restaurant_visits/run_on_dataframes.py
pipeline_dp/dataframes.py
tests/dataframes_test.py

In case if the output is not empty the schema can be deduced automatically, but if the output is empty (e.g. because all partitions are dropped by partition selection) there was an example "Empty RDD". Setting the schema fixes that.

Deriving Spark DataFrame schema on converting from RDD to DataFrame

---

analysis/contribution_bounders.py
analysis/tests/contribution_bounders_test.py
pipeline_dp/data_extractors.py
pipeline_dp/dataset_histograms/computing_histograms.py
pipeline_dp/dataset_histograms/histograms.py
pipeline_dp/dataset_histograms/sum_histogram_computation.py
pipeline_dp/pipeline_backend.py
pipeline_dp/pipeline_functions.py
tests/dataset_histograms/computing_histograms_test.py
tests/dataset_histograms/sum_histogram_computation_test.py
tests/dp_engine_test.py
tests/pipeline_backend_test.py
tests/pipeline_functions_test.py

This PR introduces computing sum histograms for multiple columns. This covers cases when DP aggregations can be presented in the pseudo-SQL terms as
```
SELECT partition_key, DP_SUM(column1), DP_SUM(columns2)
GROUP BY partition_key
```
Histograms for each column is computed independently. This is implemented by changing existing code of computing histogram on colleciton `(value: float)` to computing per key histograms of collection `(column_id:int, value:float)`

Tuning for multiple columns part 1: Computing Sum histograms for multiple columns

---

analysis/data_structures.py
analysis/dp_strategy_selector.py
analysis/parameter_tuning.py
analysis/tests/dp_strategy_selector_test.py
analysis/tests/parameter_tuning_test.py
pipeline_dp/dataset_histograms/histograms.py

This PR introduces finding candidates during tuning for computing utility analysis for case when utility analysis for multiple metrics is computed and SUM can be computed for multiple columns . This covers cases when DP aggregations can be presented in the pseudo-SQL terms as
```
SELECT partition_key, DP_COUNT(), DP_SUM(column1), DP_SUM(columns2)
GROUP BY partition_key
```

Tuning for multiple columns part 2: Find candidate parameters for multiple aggregation

---

pipeline_dp/dataset_histograms/sum_histogram_computation.py
tests/dp_engine_test.py

Beam test failed because of this type annotation, Beam uses type annotations for finding Coders.

Small annotations fix

---

pipeline_dp/dataset_histograms/histogram_error_estimator.py
tests/dataset_histograms/histogram_error_estimator_test.py

`ErrorEstimator` uses `ContributionHistograms` to estimate approximately RMSE error for different L0/Linf bounds. This PR allows to create `ErrorEstimator` for SUM (the different with COUNT, only different set of histograms)

Create error estimator for SUM

---

analysis/contribution_bounders.py
analysis/per_partition_combiners.py
analysis/pre_aggregation.py
analysis/tests/contribution_bounders_test.py
analysis/tests/utility_analysis_engine_test.py
analysis/utility_analysis_engine.py
pipeline_dp/dp_engine.py

This is used for analysis w/o cross partition contribution bounding

Create Linf contribution bounder analysis

---

examples/codelab/codelab_PipelineDP.ipynb

Specify numpy version as 1.23.5 to fix import issue
If I don't specify this version, when trying to run in Google Codelab I get the following error:
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
numpy
- Running the codelab
- instructions to reproduce: trying to run the Codelab without the change
- [ X ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ X ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ X ] I have labeled this PR with the relevant [Type …

Mark numpy version as 1.23.5 to fix import issue on example Codelab

---

.github/workflows/tests.yml

One of the PipelineDP dependencies - PyDP, doesn't have support of Mac and Windows now. As a result actions for Mac/Windows are failing. Let's first disable it.

Disable Mac/Windows tests run

---

pipeline_dp/dp_engine.py

The fix is essentially no-op:
`row=(privacy_id, parition, value)`
The goal is to drop `privacy_id`
before this PR: `lambda row: row[1:]`
in this PR:  `lambda pid, pk, v: (pk, v)`
But the first version leads to incorrect type deduction in Python Beam, as a result incorrect coders are chosen.

Minor serialization fix

---

examples/movie_view_ratings/run_without_frameworks.py
pipeline_dp/aggregate_params.py
pipeline_dp/combiners.py
pipeline_dp/dp_computations.py
tests/combiners_test.py

This PR introduces flag `output_noise_stddev`. When it set, it adds the standard deviation of applied noise, e.g. for count
`output_noise_stddev = False`: output per partition `NamedTuple(count=1.2345)`
`output_noise_stddev = True`: output per partition `NamedTuple(count=1.2345, count_noise_stddev=4.5678)`
The noise standard deviation is useful for post-processing, e.g. for computing confidence intervals.
It's implemented for COUNT, PRIVACY_ID_COUNT and SUM

Add an option to add noise standard deviation to the ouput 

---

pipeline_dp/aggregate_params.py
pipeline_dp/dp_engine.py
tests/dp_engine_test.py

It's similar to [PR](https://github.com/OpenMined/PipelineDP/pull/550), but for another function  `DPEngine.add_dp_noise`.

Add an option to add noise standard deviation to the ouput of add_dp_noise

---

pipeline_dp/budget_accounting.py
tests/budget_accounting_test.py

This PR adds support for the count argument to the `PLDBudgetAccoun.request_budget`. It's convenient when we need to apply some mechanism 10 times, we can write
```
budget = accountant.request_budget(..., count=10)
```
instead of
```
budgets = []
for _ in range(10):
budgets.append(accountant.request_budget(...))
```

Support count of operations for PLD

---

examples/movie_view_ratings/run_without_frameworks.py
pipeline_dp/aggregate_params.py
pipeline_dp/budget_accounting.py
pipeline_dp/dp_computations.py
pipeline_dp/dp_engine.py
pipeline_dp/partition_selection.py
pipeline_dp/report_generator.py
tests/budget_accounting_test.py
tests/dp_computations_test.py
tests/dp_engine_test.py
tests/partition_selection_test.py

This PR implements support of Laplace/Gaussian thresholding in `PLDBudgetAccountant`. It's implemented the following way.
PLD implementation for dp_accounting doesn't directly support thresholding, we need to track indpendently threshold delta (e.g. Gaussian Thresholding = (Gaussian Mechanism, threshold delta). `0.25*total_delta` is taken of  threshold_deltas of thresholding mechanisms (0.25 is rather arbitrary). (this implemented in budget_accountant.py)
Another complication is that the output of PLD computations for Thresholding is stddev of the noise and threshold_delta. PyDP supports only `(epsilon, delta)` for partition selection, so we need to choose  proper `(epsilon, delta)` (implementation in partition_selection.py)

Support PLD for Laplace/Gaussian thresholding

---

pipeline_dp/dp_engine.py

This PR moves `AddDPNoiseOutput` out of the function to module level. That's needed to avoid deserialization issues, internal class can't be deserialize. Otherwise this PR is no-op

Fix serialization

---

pipeline_dp/combiners.py
pipeline_dp/dp_computations.py
tests/combiners_test.py

Fixes https://github.com/OpenMined/PipelineDP/issues/551
None
- Added a failing test `test_create_accumulator_clips_individual_contributions` in which `VectorSum` combiners are not clipped as they should
- Modified `combiners.py` to do the clipping as was done in `dp_computations.py`. Test now passes.
- Removed the clipping in `dp_computations.py`. I considered adding a test that there was /no/ clipping here, but this would contradict the normal behavior where the vectors received at this stage are already clipped, so I did not.
- All existing tests now pass.

Fix #551: Clipping VectorSum per contribution
