OpenMined/PipelineDP

pipeline_dp/budget_accounting.py
tests/budget_accounting_test.py

Adds the budget accountant that manages the privacy budget.
None.
The budget_accounting_test.py file contains some simple additional tests.

Add Budget accounting

---

pipeline_dp/pipeline_operations.py
tests/pipeline_operations_test.py

Adding local group_by_key and associated tests
N/A
- Unit test

Add local group_by_key operation

---

pipeline_dp/__init__.py
pipeline_dp/dp_engine.py
pipeline_dp/pipeline_operations.py
tests/dp_engine_test.py

Implementing Per partition - bounding of each contribution and cross partition. Added flat map in pipeline_operations.py to accommodate this functionality. 
- Unit tests for bounding
- [x ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ x] My changes are covered by tests

Contribution Bounding - per partition and cross partition bounding

---

Makefile
README.md
pipeline_dp/aggregate_params.py
pipeline_dp/budget_accounting.py
pipeline_dp/dp_engine.py
pipeline_dp/pipeline_operations.py
pipeline_dp/report_generator.py
pylintrc.dms
pyproject.toml
requirements.dev.txt
tests/budget_accounting_test.py
tests/dp_engine_test.py
tests/pipeline_operations_test.py
tests/report_generator_test.py

- Add a Makefile for test, format, lint, and dev dependencies targets. 
- Linter is recommended one from https://google.github.io/styleguide/pylintrc
- Auto-formatting is recommended `yapf` from https://google.github.io/styleguide/pyguide.html using parameters `style='{based_on_style: google, indent_width: 4}'`
- Add `yapf` to poetry dependencies
- This code is for issue #19.
`pytest` `pylint` `yapf`
- Tested with `conda` environment under `Python 3.8`
- [n/a] My changes are covered by tests

Makefile targets, lint rc file, and dev requirements. Fix formatting.

---

pipeline_dp/pipeline_operations.py
tests/pipeline_operations_test.py

Implementation of accumulator reduction for Spark processing engine.
Resolves #41.
N/A
- Tests are to be added as they need the [Accumulator Framework](https://github.com/OpenMined/PipelineDP/issues/37) which is to be defined.

Implement reduce_accumulators_per_key in SparkRDDOperations (# 41)

---

pipeline_dp/dp_computations.py
tests/dp_computations_test.py

Initial implementation of [compute_dp_mean](https://github.com/OpenMined/PipelineDP/issues/36).
None.
Unit tests are included in tests\dp_computations_test.py.

[WIP] DP computing of mean and variance

---

examples/movie_view_ratings.py
pipeline_dp/pipeline_operations.py
tests/pipeline_operations_test.py

Implementation of public partition selection for Spark processing engine.
Resolves #50 .
N/A
Unit tests have been added to tests/pipeline_operations_test.py.

Public partition selection for Spark (#50)

---

.github/workflows/tests.yml

Added github actions for linting and testing of pipeline-dp, [github actions issue](https://github.com/OpenMined/PipelineDP/issues/12)
- [x ] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)

Added Github actions

---

pipeline_dp/dp_computations.py
tests/dp_computations_test.py

Implementation of [compute_dp_var](https://github.com/OpenMined/PipelineDP/issues/36).
None.
Unit tests are included in tests\dp_computations_test.py.

DP computing of variance

---

pipeline_dp/accumulator.py
tests/accumulator_test.py

Added `VectorSummationAccumulator` as per #43.  
Only implemented the summation part. The anonymization part will be implemented in a separate PR as requested by @dvadym .
None.
Added some test cases in `tests/accumulator_tests.py` next to the generic ones.

Added Vector Summation Accumulator

---

pipeline_dp/__init__.py
pipeline_dp/aggregate_params.py
pipeline_dp/budget_accounting.py
pipeline_dp/dp_computations.py
pipeline_dp/dp_engine.py
tests/accumulator_test.py
tests/budget_accounting_test.py
tests/dp_computations_test.py

This change covers step 1 of #78 
N/A
- Ran tests

Introduce new API to BudgetAccountants.

---

Makefile
examples/movie_view_ratings.py
pipeline_dp/accumulator.py
tests/accumulator_test.py

Related to https://github.com/OpenMined/PipelineDP/issues/53.
Also includes some smaller improvements.
None
- Unit tests
- Manual E2E test with movie ratings
- [+] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [+] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [+] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [+ ] My changes are covered by tests

Implement PrivacyIdCount

---

pipeline_dp/budget_accounting.py
tests/budget_accounting_test.py

Implementing count. I haven't added tests yet I want to make sure the implementation looks correct first
N/A
- No tests yet

Implement the new count field in the mechanism_spec.

---

pipeline_dp/dp_computations.py
tests/accumulator_test.py
tests/dp_computations_test.py

This PR implements using safe Laplace/Gaussian noise from [C++ Google DP library](https://github.com/google/differential-privacy), which is wrapped in [PyDP](https://github.com/OpenMined/PyDP).

Use safe Laplace and Gaussian noise

---

pipeline_dp/aggregate_params.py
tests/dp_engine_test.py
tests/pipeline_operations_test.py

This PR makes PipelineDP work even if spark is not installed

Minimize spark dependencies

---

pipeline_dp/private_spark.py
tests/private_spark_test.py

Implementation of map and flat_map transformations on PrivateRDD.
Resolves #70.
N/A
Unit tests have been added.

Map and FlatMap on PrivateRDD

---

pipeline_dp/__init__.py
pipeline_dp/dp_engine.py
pipeline_dp/private_beam.py

1.Added stage name in group_by_key
2.Converted (partition_key, [sum]) -> (partition_key, sum) in Sum for PrivatePCollection

Minor fixes

---

pipeline_dp/accumulator.py
pipeline_dp/dp_engine.py
pipeline_dp/pipeline_operations.py
tests/dp_engine_test.py

Fixes #110.
n/a
- Unit tests
- movie ratings example

Implement adding empty public partitions

---

pipeline_dp/aggregate_params.py
pipeline_dp/private_beam.py
tests/private_beam_test.py

Add Count Transform to Beam's public API. Mimicking the `Sum` transform.
- Unit tested.

Add Count Transform to Beam's public API.

---

examples/__init__.py
examples/example_utils.py
examples/movie_view_ratings.py
examples/movie_view_ratings_spark.py
examples/parse_utils.py
pipeline_dp/aggregate_params.py

The main example (movie_view_ratings.py) is quite elaborate and complicated, since it tries to demonstrate all features at once. Furthermore, it doesn't demonstrate the developer-facing Spark and Beam APIs.
This creates a simple, minimalistic example for the Spark API.
List any dependencies that are required for this change.
Manually. We don't have automated tests for the examples yet.

Create a minimalistic example for Spark API

---

examples/example_utils.py
examples/movie_view_ratings.py
examples/movie_view_ratings_beam.py

An example similar to the one we already have for Spark.
By running the example manually. We don't have automated tests for examples atm.

Add a simplistic example using Apache Beam.

---

pipeline_dp/combiners.py
tests/combiners_test.py

Adds sum combiners and compound combiners. Please take a look. If it looks OK I will add tests.
None for now, will affect aggregations if we are going to use the combiners to replace the old accumulators
Prototype for now, will add tests if it's OK

Adds sum combiners and compound combiners.

---

pipeline_dp/aggregate_params.py
pipeline_dp/private_beam.py
tests/private_beam_test.py

Make public partitions optional
Delete value_extractor because it isn't used
Clean-up CountParams comments
Test that Count result is sensible

Fix and test Beam count  and PrivacyIdCount 

---

pipeline_dp/combiners.py
pipeline_dp/dp_engine.py
tests/combiners_test.py
tests/dp_engine_test.py

Uses combiners in dp engine. Please take a look to see if things look good. Will fix tests later. 
There is a potential clean up to use named tuple in CompoundCombiners to make code cleaner. Will do that after the logics look correct.
Could affect all places using dp aggregations.
Most unit tests except for two. One is still missing mean combiners and the other uses mock of Accumulator. Will fix after the logics look correct.

Uses combiners in dp engine.

---

pipeline_dp/dp_engine.py
tests/private_beam_test.py

... return sensible result
plus delete a forgotten TODO

Test Beam Count, Sum, PIdCoun with pub partitions

---

README.md
examples/movie_view_ratings_beam.py
examples/movie_view_ratings_spark.py

Update top-level README.md file to include a better description and a code snippet. We'll have more documentation and 
examples on the web-site, but it's good to have some basic info in README.md
A docs-only change, no tests.

Update top-level README.md file to include a better description and a code snippet.

---

pipeline_dp/__init__.py
pyproject.toml

It was accidentally changed on [PR](https://github.com/OpenMined/PipelineDP/pull/166)

Fit style in project file

---

pipeline_dp/aggregate_params.py
pipeline_dp/dp_engine.py
tests/accumulator_test.py
tests/combiners_test.py
tests/dp_engine_test.py

1. Cleans up checking methods for AggregateParams for reusing.
2. Cleans up tests in combiners_test

Cleans up aggregate checking methods for reusing.

---

examples/restaurant_visits.ipynb

Completely rewrote the colab:
- added DP description, example description, etc
- added Core API examples
- added Beam API examples

Revamp the colab

---

README.md
examples/restaurant_visits.ipynb

Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
List any dependencies that are required for this change.
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

Add colab to landing README and fix colab name

---

README.md
examples/movie_view_ratings_beam.py
examples/movie_view_ratings_local.py
examples/movie_view_ratings_spark.py
pipeline_dp/aggregate_params.py

Improving documentation in examples.

---

utility_analysis/non_private_combiners.py

Fixes for utility analysis for namedtuple change of the metrics in https://github.com/OpenMined/PipelineDP/commit/8f730292f45628c46949eff16d190365a5e3d42b. Because the metrics of the utility analysis are not directly exposed to customers (they are used in visualization). We don't change compute_metrics for now.

Fixes for utility analysis to include metrics_names.

---

pipeline_dp/private_spark.py
tests/private_spark_test.py

Add  mean to private Spark
- Unit tests

Add  mean to private Spark

---

tests/accumulator_test.py
tests/private_beam_test.py

Quick fixes accumulator tests. Accumulators shouldn't matter too much in our code base going forward. Probably we want to remove them altogether later.

Fixes accumulator tests.

---

README.md
utility_analysis/README.md

Updates utility analysis readme

Updates utility analysis readme.

---

_config.yml

Change hero text to remove references to "the latest" and "anonymization."

Update hero text

---

pipeline_dp/budget_accounting.py
pipeline_dp/dp_engine.py
pipeline_dp/pipeline_backend.py

Implement abstract class Annotator to be able to annotate PipelineDP pipelines.

Implement abstract class Annotator

---

pipeline_dp/aggregate_params.py
pipeline_dp/dp_engine.py
tests/dp_engine_test.py

This PR introduces support for a max contributions per user bounding. This PR fixes #263.
N/A
Test cases have been added for the newly added method.

Support for max_contribution_per_user contribution bounding as per #263

---

pipeline_dp/contribution_bounders.py
pipeline_dp/dp_engine.py
tests/contribution_bounders_test.py
tests/dp_engine_test.py

This PR extracts Contribution bounding to `ContributionBounder` class. There is refactoring, no changes in functionality.

Contribution bounding refactoring

---

pipeline_dp/dp_computations.py
tests/dp_computations_test.py

Implement function which returns noise type and standard deviation from `AggregateParams`

Implemented compute_count_noise_params 

---

pipeline_dp/budget_accounting.py
pipeline_dp/contribution_bounders.py
pipeline_dp/dp_computations.py
tests/contribution_bounders_test.py

It contains:
1. Adding missing copyright headers
2. Fixing coding style: importing of modules instead of importing classes

Polishings

---

.github/workflows/tests.yml
utility_analysis_new/combiners.py
utility_analysis_new/tests/combiners_test.py

This is the implementation for Count Accumulator Combiner that will be used in Utility Analysis.
None
- Unit testing

Count accumulator combiner for utility analysis

---

utility_analysis_new/__init__.py

Adding the default init file to the new folder.
None
N/A.

Add the default init file.

---

.github/workflows/tests.yml
utility_analysis_new/combiners.py

Fix a broken test that will now be run in the github workflow (previously it was missed).
N/A
- N/A

Add utility analysis new to github workflow, Fix broken test

---

utility_analysis_new/poisson_binomial.py
utility_analysis_new/tests/combiners_test.py
utility_analysis_new/tests/poisson_binomial_test.py

Those computations will be used in partition selection utility analysis

Poisson binomial distribution computations

---

utility_analysis_new/combiners.py
utility_analysis_new/dp_engine.py
utility_analysis_new/tests/combiners_test.py
utility_analysis_new/tests/dp_engine_test.py

Add a sum combiner for utility analysis.
None
- Unit tests.

Sum Utility Analysis combiner and tests.

---

utility_analysis_new/dp_engine.py

Fix the ordering in the if statement so that the collection is tested against the value.
N/A
- Testing will follow when compound combiners is fully implemented.

Fix ordering error in compound combiners.

---

utility_analysis_new/combiners.py
utility_analysis_new/dp_engine.py
utility_analysis_new/tests/combiners_test.py

Combiner implementation for privacy ID Count.
N/A
- Unit tests in combiners_test

Privacy ID Count combiner implementation and tests

---

requirements.dev.txt
utility_analysis_new/combiners.py
utility_analysis_new/tests/combiners_test.py

Along the way the version PyDP is updated.

Fix keep probability computations for utility analysis

---

examples/restaurant_visits/run_without_frameworks_utility_analysis.py
utility_analysis_new/combiners.py
utility_analysis_new/tests/utility_analysis_test.py

This PR contains:
1. Addressing comments from [PR](https://github.com/OpenMined/PipelineDP/pull/337)
2. Update an example to get aggregate utility analysis metrics

Polishing in Aggregate Utility Analysis

---

examples/restaurant_visits/run_without_frameworks_tuning.py
pipeline_dp/pipeline_backend.py
tests/pipeline_backend_test.py
utility_analysis_new/parameter_tuning.py
utility_analysis_new/tests/parameter_tuning_test.py

1. Renamed `PipelineBackend: combiner_per_key -> reduce_per_key` and fixes for Beam
2. 1 import fix
3. A minor example fix

Different fixes and polishing

---

analysis/data_structures.py
analysis/metrics.py
analysis/tests/utility_analysis_test.py
analysis/utility_analysis.py
analysis/utility_analysis_engine.py
examples/restaurant_visits/run_without_frameworks_utility_analysis.py

That's convenient for understanding which result corespond to which input parameters

Add AggregateParams to utility analysis results

---

analysis/metrics.py
analysis/parameter_tuning.py

Filling this dataclasses will be done in the following PRs.

Refactor analysis output metrics: part 1 Adding new metrics

---

examples/movie_view_ratings/pipelinedp_spark_on_aws_glue.ipynb

Added notebook that can be used on AWS Glue for PipelineDP with SparkRDDBackend as backend.
I've included simple instructions at the beginning of the notebook with links to help set everything up on AWS.
- Created job on AWS Glue and executed notebook.
- Here's a screenshot of the results to show it worked:

Added notebook with example for spark on AWS glue

---

contributing/Dockerfile

Fixed being able to use beam or spark inside container.

Fixed Dockerfile to be able to use beam or spark inside container

---

analysis/cross_partition_combiners.py
analysis/metrics.py
analysis/tests/cross_partition_combiners_test.py

Those helpers will be used in the following PRs

Refactor analysis output metrics: part 4 Dataclass helpers

---

pipeline_dp/aggregate_params.py
tests/aggregate_params_test.py

Metric equal operator fix

---

tests/dp_computations_test.py

Expected flakiness is decreased from 2\*10^-3 to 2\*10^-4

Decrease test flakiness

---

pipeline_dp/private_beam.py

`CustomCombiner` is the way how client can implement custom DP aggregation, with PipelineDP manages all infrastructure stuff (Contribution bounding, Partition selection, budget management etc).
In the initial version of this API, it was assumed that `CustomCombiner` requests the budget only once. But 
`CustomCombiner` might need to request multiple budget objects, for example for computing mean, it's needed to add noise 2 times - for count and sum.  This PR changes that. `CustomCombiner` can use any structure for keeping budgets (e.g. dictionary) rather than 1 budget object.

Small updates of typing and documentation for CustomCombiner

---

analysis/parameter_tuning.py
analysis/tests/parameter_tuning_test.py
pipeline_dp/private_contribution_bounds.py
tests/private_contribution_bounds_test.py

Add functionality to search parameters in a grid with "constant" (from 0.1% to 1%) relative step.

Search parameters grid with constant relative step

---

analysis/parameter_tuning.py
pipeline_dp/dataset_histograms/computing_histograms.py
pipeline_dp/dataset_histograms/histograms.py

It contains some small changes
1. Not changing input objects in map
2. Formatting of docstrings

Small polishing

---

analysis/dataset_summary.py
analysis/tests/dataset_summary_test.py

Public partition summary, namely:
```
class PublicPartitionsSummary:
num_dataset_public_partitions: int  # in dataset and public partitions
num_dataset_non_public_partitions: int # in dataset and not in public partitions
num_empty_public_partitions: int # not in dataset and in public partitions
```

Compute public partition summary

---

analysis/contribution_bounders.py
analysis/tests/contribution_bounders_test.py
analysis/tests/utility_analysis_engine_test.py
analysis/utility_analysis_engine.py
examples/restaurant_visits/run_without_frameworks_tuning.py

On [PR](https://github.com/OpenMined/PipelineDP/pull/477) it was changed the order in which extracting columns from the data was performed. As a result it broke running utility analysis on pre-aggregated data. This PR fixed that

Fix Utility analysis on preagregation

---

.github/workflows/tests.yml
pipeline_dp/__init__.py
pyproject.toml
requirements.dev.txt
setup.cfg
setup.py
tests/budget_accounting_test.py
tests/dp_engine_test.py
tests/pipeline_backend_test.py

Also add running tests for Python 3.11

Update version to 0.2.1rc4 and PyDP dependecy to 1.1.4

---

contributing/Dockerfile

Fix the Python version in the Dockerfile.
None.
Not at all.

Fix python version in Dockerfile

---

README.md

Refer to the attack model in README

---

pipeline_dp/pipeline_backend.py
tests/pipeline_backend_test.py

Side input is a singleton collection which is passed as an argument to a mapper function. Previously map and flat_map with side input were already added.

Introduce filter_with_side_input
